---
- name: Setup Ubuntu development VM
  hosts: all
  become: true

  tasks:
    - name: Install prerequisites
      apt:
        update_cache: true
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Add Docker repo key
      shell:
        cmd: >
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg
          | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        creates: /usr/share/keyrings/docker-archive-keyring.gpg
        warn: false

    - name: Create repo file
      copy:
        src: docker.list
        dest: /etc/apt/sources.list.d/docker.list

    - name: Install docker
      apt:
        update_cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Create docker group
      group:
        name: docker

    - name: Add vagrant to docker group
      user:
        name: vagrant
        groups:
          - docker
        append: true

    - name: Install virtual environment support
      apt:
        name: python3-venv
